# Generated by Django 5.1.7 on 2026-03-21 09:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='MetaCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('access_token', models.TextField()),
                ('token_last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishingTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_key', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('drive_folder_id', models.CharField(blank=True, max_length=255)),
                ('drive_folder_url', models.URLField(blank=True)),
                ('posts_per_day', models.PositiveSmallIntegerField(default=1)),
                ('posting_window_start', models.TimeField(default=datetime.time(10, 0))),
                ('posting_window_end', models.TimeField(default=datetime.time(18, 0))),
                ('default_caption', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_posted_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=50)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='scheduler.metacredential')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='PostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('drive_file_id', models.CharField(blank=True, max_length=255)),
                ('drive_file_name', models.CharField(blank=True, max_length=255)),
                ('meta_creation_id', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_logs', to='scheduler.publishingtarget')),
            ],
            options={
                'ordering': ['-scheduled_for', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('external_id', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='scheduler.metacredential')),
            ],
            options={
                'ordering': ['platform', 'name', 'username'],
                'unique_together': {('credential', 'platform', 'external_id')},
            },
        ),
        migrations.AddField(
            model_name='publishingtarget',
            name='facebook_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'platform': 'facebook'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facebook_targets', to='scheduler.socialaccount'),
        ),
        migrations.AddField(
            model_name='publishingtarget',
            name='instagram_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'platform': 'instagram'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_targets', to='scheduler.socialaccount'),
        ),
    ]
