# Generated by Django 5.1.7 on 2026-03-21 12:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=255)),
                ('drive_file_name', models.CharField(max_length=255)),
                ('variant', models.CharField(default='default', max_length=50)),
                ('public_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('public_filename', models.CharField(max_length=255)),
                ('local_path', models.CharField(blank=True, max_length=500)),
                ('source_mime_type', models.CharField(blank=True, max_length=120)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='scheduler.publishingtarget')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('target', 'drive_file_id', 'variant')},
            },
        ),
    ]
