# Generated by Django 5.1.7 on 2026-03-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_mediaasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishingtarget',
            name='posting_times',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
