# Generated by Django 5.1.7 on 2026-03-23 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_publishingtarget_posting_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishingtarget',
            name='ai_auto_caption_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publishingtarget',
            name='ai_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publishingtarget',
            name='ai_language',
            field=models.CharField(default='Hinglish', max_length=50),
        ),
        migrations.AddField(
            model_name='publishingtarget',
            name='ai_last_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishingtarget',
            name='ai_last_report_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publishingtarget',
            name='ai_tone',
            field=models.CharField(default='Professional', max_length=50),
        ),
        migrations.CreateModel(
            name='AIMediaInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=255)),
                ('drive_file_name', models.CharField(max_length=255)),
                ('source_mime_type', models.CharField(blank=True, max_length=120)),
                ('primary_category', models.CharField(blank=True, max_length=120)),
                ('secondary_tags', models.JSONField(blank=True, default=list)),
                ('primary_caption', models.TextField(blank=True)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('short_caption', models.TextField(blank=True)),
                ('long_caption', models.TextField(blank=True)),
                ('hindi_caption', models.TextField(blank=True)),
                ('english_caption', models.TextField(blank=True)),
                ('hinglish_caption', models.TextField(blank=True)),
                ('duplicate_risk', models.CharField(blank=True, max_length=20)),
                ('duplicate_reason', models.TextField(blank=True)),
                ('quality_risk', models.CharField(blank=True, max_length=20)),
                ('quality_issues', models.JSONField(blank=True, default=list)),
                ('safe_to_post', models.BooleanField(default=True)),
                ('translated_hindi', models.TextField(blank=True)),
                ('translated_english', models.TextField(blank=True)),
                ('translated_hinglish', models.TextField(blank=True)),
                ('best_posting_times', models.JSONField(blank=True, default=list)),
                ('best_posting_reason', models.TextField(blank=True)),
                ('report_summary', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_media_insights', to='scheduler.publishingtarget')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('target', 'drive_file_id')},
            },
        ),
    ]
