# Generated by Codex on 2026-05-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0004_publishingtarget_ai_auto_caption_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledPostRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scheduled_for", models.DateTimeField()),
                ("drive_file_id", models.CharField(blank=True, max_length=255)),
                ("drive_file_name", models.CharField(blank=True, max_length=255)),
                ("drive_mime_type", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("partial_success", "Partial success"),
                            ("success", "Success"),
                            ("skipped", "Skipped"),
                            ("backoff", "Backoff"),
                            ("failed", "Failed"),
                            ("misconfigured", "Misconfigured"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("platform_status", models.JSONField(blank=True, default=dict)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("lock_owner", models.CharField(blank=True, max_length=120)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_runs",
                        to="scheduler.publishingtarget",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_for", "target_id"],
                "unique_together": {("target", "scheduled_for")},
            },
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="drive_checksum",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="drive_modified_time",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="source_fingerprint",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="postlog",
            name="scheduled_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="post_logs",
                to="scheduler.scheduledpostrun",
            ),
        ),
        migrations.AlterField(
            model_name="postlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledpostrun",
            index=models.Index(fields=["status", "next_retry_at"], name="scheduler_s_status_140f89_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduledpostrun",
            index=models.Index(fields=["target", "scheduled_for"], name="scheduler_s_target__47eb32_idx"),
        ),
    ]
