# Generated by Django 5.1.7 on 2026-05-29 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0005_scheduledpostrun_media_fingerprint_postlog_run"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaCredentialEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credential_label", models.CharField(blank=True, max_length=120)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("sync_failed", "Sync failed"),
                            ("archived", "Archived"),
                            ("restored", "Restored"),
                        ],
                        max_length=40,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=80)),
                ("actor", models.CharField(blank=True, max_length=120)),
                ("note", models.TextField(blank=True)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="scheduler.metacredential",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
