# Generated by Django 5.1.7 on 2026-06-04 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0006_metacredentialevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="metacredential",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meta_credentials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="publishingtarget",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publishing_targets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publishingtarget",
            name="sync_key",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="publishingtarget",
            constraint=models.UniqueConstraint(
                fields=("owner", "sync_key"), name="uniq_owner_sync_key"
            ),
        ),
    ]
